### ISSUE TITLE
Ivy file not found in cache during build

### ISSUE THREAD

**Issue by William-Hill** [ESGF/esgf-dashboard#10]
When running esgf-dashboard's build script, an error occurs during the publish_local stage due to a missing Ivy file.

Stack Trace:
/Users/hill119/Development/esgf-dashboard/build.xml:854: org.esgf#esgf-dashboard;1.5.4: java.lang.IllegalStateException: Ivy file not found in cache for org.esgf#esgf-dashboard;1.5.4!

**Comment by William-Hill** [comment]
This error still occurs when trying to build at LLNL.  Reopening.

**Comment by alenu** [comment]
The issue has been solved with the new version of the software.
