### ISSUE TITLE
ip.service status not reliable

### ISSUE THREAD

**Issue by SebastienGardoll** [ESGF/esgf-dashboard#11]
/usr/local/esgf-dashboard-ip/bin/ip.service implements the status command with pgrep that only looks at the first 15 characters of the process command lines. If the dashboard is restarted manually, pgrep doesn't return any pid because the command line is over 15 characters.

It should be fixed using the option -f : pgrep -f $SERVICE

**Comment by gardoll** [comment]
And for every execution of pgrep

**Comment by mmirto** [comment]
The ip.service file has been updated as you suggested. Could you check that and let me know? Many thanks.

**Comment by gardoll** [comment]
In fact, pgrep is not a good idea:

**Comment by gardoll** [comment]
It seems that pgrep -f prevents the dashboard to start in the last version v2.6.7 .

**Comment by gardoll** [comment]
pgrep -f prevents the dashboard to start because when the ip.service script is executed, the process that run the script has the 'esgf-dashboard-ip' string in its path. So the script think that the dashboard daemon is already running.

**Comment by mmirto** [comment]
we will do some tests to solve this problem

**Comment by alenu** [comment]
Issue solved with the new version of the software.
