### ISSUE TITLE
Fails to install esgf_dashboard

### ISSUE THREAD

**Issue by omula** [ESGF/esgf-dashboard#7]
/usr/local/bin/esg-dashboard: line 611: /usr/local/uvcdat/2.2.0/bin/easy_install esgf_dashboard-0.0.1-py2.7.egg: No such file or directory
easy_install is not available in uvcdat package.

```
[root@esgf-dev bin]# rpm -ql uvcdat-2.2.0-1.x86_64|grep -i easy_install
[root@esgf-dev bin]# 
```

**Comment by alenu** [comment]
Issue solved with the new version of the software.
