### ISSUE TITLE
Schema migration failed in 2.5.13 upgrade from 2.4 (test VM)

### ISSUE THREAD

**Issue by sashakames** [ESGF/esgf-dashboard#9]
During the install script execution:

  File "/usr/local/conda/envs/esgf-pub/lib/python2.7/site-packages/sqlalchemy/en
gine/default.py", line 331, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) relation "esgf_migrate_version" does not exist
LINE 1: UPDATE esgf_migrate_version SET version=9 WHERE esgf_migrate...
               ^
 'UPDATE esgf_migrate_version SET version=%(version)s WHERE esgf_migrate_version.version = %(version_1)s AND esgf_migrate_version.repository_id = %(repository_id_1)s' {'version_1': 8, 'version': 9, 'repository_id_1': 'ESGF Dashboard schema migration'}
ERROR: Could not create esgf dashboard database tables in esgcet

**Comment by alenu** [comment]
Issue solved with the new version of the software.
